### PR TITLE
Add support for reloading in React Native environment

### PR DESCRIPTION
**Pull request by rasom**
Currently `lein-figwheel >= 0.5.9` crashes with `Reload not defined for this platform` error message in React Native applications ([re-natal](https://github.com/drapanjanas/re-natal)). This commit fixes the problem.

### CODE REVIEW

**Comment by bhauman** [comment]
Well it's pretty obvious we are going to have to start moving to an idea of traits rather than going by an environment.

But for now I'd like to have a `react-native-env?` and a `:react-native` key returned by `host-env?`

And then look for the spots that are using `(html-env?)` as a behavior switch and include react native as needed.

Ideally if you find a spot that is testing for `(html-env?)` that needs to include `react-native` then it would be best to create a function that tests for the trait that is being looked for

```
(defn trait-console? [] (exists? js/console))

(defn trait-console-warn? [] (and (trait-console?) (exists? js/console.warn))
``` 

How does that sound?

**Comment by bhauman** [comment]
Those trait functions would go in the `utils.cljs`

**Comment by rasom** [comment]
Thanks, @bhauman, sounds reasonable.

I've just added updates in another commit, let's see if I understand you correctly.

**Comment by bhauman** [comment]
The only other thing I worry about, is if goog.global.navigator will exist in all environments?

**Comment by rasom** [comment]
> The only other thing I worry about, is if goog.global.navigator will exist in all environments?

You are right, I'm not sure that it exists in all environments

**Comment by tiensonqin** [comment]
@rasom I got this same problem when using React Native with Exponent [exponent-cljs-template](https://github.com/tiensonqin/exponent-cljs-template), so thanks for your work.

I've tested `goog.global.navigator` on these 4 environments:
1. html, exists
2. worker, exists
3. node, not exists
4. react-native, exists and `goog.global.navigator.product` equals to `react-native`.

https://github.com/facebook/react-native/issues/1331

**Comment by rasom** [comment]
@tiensonqin, thanks for checking this. 
I suppose that ([commit](https://github.com/bhauman/lein-figwheel/pull/524/commits/db9a4ebcc30008748d460a6d00203781c9134e60#diff-a5c08b241e285fd47f9d6dce36c97595R17))

```clojure
(and (exists? goog/global.navigator)
     (= goog/global.navigator.product "ReactNative")
```
will be safe in all environments.

**Pull request merged**
