### PR TITLE
Add Circle CI testing

### PR DESCRIPTION
**Pull request by danielcompton**
- Add a circle.yml file to test the Clojure parts of sidecar and support
- Add a badge to the README with test status

I'm happy to add CLJS testing for example and support if you let me know how you normally run those tests. Otherwise I can add in doo testing?

To setup CircleCI, just go to [circleci.com](https://circleci.com) and sign up with your GitHub credentials. Then you can enable figwheel and away you go.

You can see test results here: https://circleci.com/gh/danielcompton/lein-figwheel/4

### CODE REVIEW

**Comment by danielcompton** [comment]
I've fixed the merge conflicts on this, are you interested in adding CircleCI? If not then I'll close it.

**Comment by bhauman** [comment]
Sorry man.  I never got around to this because my testing discipline in figwheel is horrible. I haven't looked at the tests in quite a while

**Comment by danielcompton** [comment]
No worries. Maybe you could start with the CLJ tests, and add more over time?

**Comment by danielcompton** [comment]
Hey, I've updated this to use the new scripts/install command. Are you interested in adding this? It's especially helpful for contributors making changes to make sure they haven't broken something.

**Comment by bhauman** [comment]
What other steps need to be taken here? Do I have to set up an account on CircleCI?

**Comment by danielcompton** [comment]
Yep, just go to CircleCI and you can authenticate with GitHub, no extra count required.

**Pull request merged**
