### PR TITLE
Add editorconfig file for consistent whitespace

### PR DESCRIPTION
**Pull request by danielcompton**
This PR adds an editorconfig file which provides consistent formatting rules for all editors to follow. In particular it ensures there is always a final newline in a file and trailing whitespace is trimmed.

The existing repo was updated with the [eclint](https://www.npmjs.com/package/eclint) tool.

### CODE REVIEW

**Comment by arichiardi** [comment]
Oh this is awesome,, thanks it will make `git add --patch` shorter for contributors  😀

**Comment by danielcompton** [comment]
You can see that there are no significant changes through the `w=1` URL param: https://github.com/bhauman/lein-figwheel/pull/522/files?w=1

**Comment by bhauman** [comment]
Thanks!! Now to get editorconfig going in emacs

**Comment by bhauman** [comment]
Well that was easy! Thanks!

**Pull request merged**
