### PR TITLE
Allows the passage of :server-opts to configure the http-kit server.

### PR DESCRIPTION
**Pull request by Bauerpauer**
This is most useful for allowing the configuration of the `:max-body` option for http-kit.

Also, fixes the configuration check for :server-logfile

### CODE REVIEW

**Comment by Bauerpauer** [comment]
@bhauman, I ran into issues trying to upload large files while in development mode. There was seemingly no other way to get custom configuration into the `run-server` call, so here we are...

Also, `0.5.1-SNAPSHOT` was failing to validate my config w/ `:server-logfile` set.

**Comment by bhauman** [comment]
The party line on the built in server limitations is that it's only intended for initial RAD and that as soon as it stops meeting your needs, its time to plunk down and create your own server which is an inevitable step anyway.  

Including :server-opts marries figwheel to HttpKit which is not something I want.

**Comment by bhauman** [comment]
Thanks for the submission though!  I'm still trying to get this config validation thing working :)

**Comment by Bauerpauer** [comment]
That's understandable. Any tips on doing such a thing? I'm not intending to use the Figwheel server for my deployed app, it's just a real pain to have to switch servers every time I want to test the upload feature of my app with a large file.

**Comment by Bauerpauer** [comment]
Thanks for the tip on Slack. Running a separate process w/ `lein ring server-headless` works just fine.

**Pull request closed without merging**
