### PR TITLE
Write nREPL port number to .nrepl-port file

### PR DESCRIPTION
**Pull request by r0man**
When connecting to an nREPL server started by Figwheel via `M-x cider-connect` you have to enter the hostname and the port of the nREPL server. The hostname defaults to `localhost`, and the port number is taken from the `.nrepl-port` file if it exists. This commit writes the port number taken from the Figwheel options to that file when starting a nREPL server. This allows you to invoke `M-x cider-connect` and hit enter 2 times, instead of entering the port number manually.

### CODE REVIEW

**Comment by r0man** [comment]
Hello @bhauman, what do you think of this little enhancement?

**Comment by danielcompton** [comment]
Relates to #258

**Comment by r0man** [comment]
Oops, haven't seen this.

**Comment by bhauman** [comment]
You can use cider-jack-in now:
https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl

**Pull request closed without merging**
