### PR TITLE
Alternateve extraction of location info from exception

### PR DESCRIPTION
**Pull request by arichiardi**
This is the bag of Christmas gift that I would like Santa to bring to `boot`'s users :smile: 

Ok at the moment just one, and hopefully it will stay one, but I guess we can wait for the merge until I have a stable working prototype of my [boot-reload PR](https://github.com/adzerk-oss/boot-reload/pull/105).

### CODE REVIEW

**Comment by arichiardi** [comment]
For some consistency on the first commit, see also [here](https://github.com/clojure/clojurescript/blob/cfbaba0f7f2f9f918896528ca8e814831218458b/src/main/clojure/cljs/analyzer.cljc#L633).

**Comment by arichiardi** [comment]
Ok, i misread the code as I thought the content URL was built above. Will remove the commit and fix the title. Sorry about that 😀😀

**Comment by arichiardi** [comment]
@bhauman I think my `boot-reload` PR is ready for a go, which means that I would like to nudge and extort an opinion on this PR from you :smile:

**Comment by bhauman** [comment]
Actually this PR is on the wrong track.  The exception parsing goes through a series of stages. The stage you are hooking into has nothing to do with CLJS exceptions. The stage you hooked into is only for loading clojure code into the runtime.

I'm not sure what the best way to handle this is as I don't know the shape of the data. Look at the function `parse-analysis-error` and make sure it can read your exception data.

It looks like `parse-analysis-error` is doing what it's supposed to do.

**Comment by bhauman** [comment]
`parse-exception` doesn't work for you?

**Comment by bhauman** [comment]
Oh wait! I see this new Clojure Loading error code is catching your exceptions before they get into the flow. This may be a bug on my part let me check.

**Comment by arichiardi** [comment]
This one? https://github.com/bhauman/lein-figwheel/blob/99e1ab011a53c6d84466663dba0eca64b5e01783/sidecar/src/figwheel_sidecar/cljs_utils/exception_parsing.clj#L245

From what I saw: `parse-exception` -> `parse-inspected-exception` -> `parse-loaded-clojure-exception` -> `parse-loaded-clojure-exception`

**Comment by arichiardi** [comment]
After Slack conversation and after your suggestion I was able to convert my exception data to the `inspect-exception` format and now everything works without patches!

Closing and as usual thanks for your help!

**Pull request closed without merging**
