### PR TITLE
reinstate nodejs support

### PR DESCRIPTION
**Pull request by TerjeNorderhaug**
Reinstates support for nodejs broken in 0.3.7:

1.  Injects connection script also for node;
2.  Expects :target property of :compiler to be :nodejs

### CODE REVIEW

**Comment by bhauman** [comment]
Thats funny we were both working on this at the same time. :)

**Comment by bhauman** [comment]
Thanks for working on this.  I really appreciate it.

**Comment by TerjeNorderhaug** [comment]
Thanks for your quick response on the issue. Guess the pull request can be closed then.

**Comment by bhauman** [comment]
Glad you brought my attention to it.  I don't think `:main` for Node was even an option when I first wrote this code.

**Pull request closed without merging**
